name: Auto merge pull requests with label "study-plan" and non-main branch

on:
  pull_request:
    types: -labeled

jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - id: automerge
        uses: "pascalgn/automerge-action@v0.15.6"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          merge-method: merge
          merge-labels: study-plan
          delete-branch: false
          pull-request-filter: >
            head != 'main' && contains(github.event.pull_request.labels.*.name, 'study-plan')
