name: Auto Merge Study Plan
on:
  pull_request:
    types: [opened, reopened]

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Auto Merge Study Plan
        uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const labels = context.payload.pull_request.labels
            const hasStudyPlanLabel = labels.some(label => label.name === 'study-plan')
            if (hasStudyPlanLabel) {
              github.pulls.merge({
                pull_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo
              })
            }
