name: Auto merge pull requests with label "study-plan" and non-main branch

on:
  schedule:
    - cron: "0 13 * * 1" # Run every Monday at 1pm

jobs:
  auto_merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Auto merge pull requests
        uses: pascalgn/automerge-action@v0.13.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          base: main
          merge-method: merge
          merge-labels: study-plan
          delete-branch: false
          pull-request-filter: >
            head != 'main' && contains(github.event.pull_request.labels.*.name, 'study-plan')
